# Generated by Django 2.1.5 on 2019-03-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
