# Generated by Django 2.1.5 on 2019-03-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190316_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neededitem',
            old_name='location',
            new_name='address',
        ),
    ]
