# Generated by Django 2.1.5 on 2019-03-17 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_neededitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neededitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 17, 5, 38, 42, 333963, tzinfo=utc)),
        ),
    ]
