# Generated by Django 2.1.5 on 2019-03-17 14:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20190316_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='neededitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neededitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 17, 14, 5, 0, 22064, tzinfo=utc)),
        ),
    ]
