# Generated by Django 2.1.5 on 2019-03-17 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190317_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neededitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 17, 14, 7, 41, 634260, tzinfo=utc)),
        ),
    ]
