# Generated by Django 2.1.5 on 2019-03-17 14:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20190317_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='neededitem',
            name='donated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neededitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 17, 14, 19, 6, 788605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='neededitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
