# Generated by Django 2.1.5 on 2019-03-18 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190317_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='org_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='neededitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 18, 16, 58, 30, 373916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_url',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wish_list',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
