# Generated by Django 2.1.5 on 2019-03-18 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190318_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neededitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 18, 17, 4, 12, 817991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wish_list',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
